version: "3.8"

networks:
  proxy:
    external: true

services:
  traefik:
    domainname: docker.local
    container_name: traefik
    # The official v2 Traefik docker image
    image: traefik:v2.3
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      - "--providers.docker=true"
      - "--providers.docker.network=proxy"
      - "--providers.docker.exposedbydefault=true"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--entrypoints.http.address=:80"
      - "--log.level=DEBUG"
      - "--log.filePath=/etc/traefik/traefik.log"
      - "--accesslog=true"
      - "--providers.file.directory=/etc/traefik/config"
      - "--providers.file.watch=true" 
    restart: unless-stopped
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - ${traefikConfigDir}:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
      - proxy
    dns:
      - 192.168.1.31
      - 1.1.1.1

  pihole:
    container_name: pihole
    domainname: docker.local
    networks:
      - proxy
    hostname: pihole
    image: pihole/pihole:latest
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      # - '67:67/udp'
      # - '0.0.0.0:8053:80/tcp'

    restart: unless-stopped
    volumes:
      - ${USERDIR}/docker/pihole/pihole:/etc/pihole
      # - ${USERDIR}/docker/pihole/pihole.log:/var/log/pihole.log
      - ${USERDIR}/docker/pihole/dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    environment:
      - ServerIP=${SERVER_IP}
      - TZ=${TZ}
      - WEBPASSWORD=PIHOLEWEBPASSWORD
      - VIRTUAL_HOST=pihole.dangernoodle.co.za
      - VIRTUAL_PORT=80
      - DNS1=127.0.0.1
      - DNS2=1.1.1.1

    labels: 
      - "traefik.http.routers.pihole.rule=Host(`pihole.dangernoodle.co.za`)"
      - "traefik.http.routers.pihole.entrypoints=http"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.http.middlewares.test-redirectregex.redirectregex.regex=^http://pihole.dangernoodle.co.za"
      - "traefik.http.middlewares.test-redirectregex.redirectregex.replacement=http://pihole.dangernoodle.co.za/admin"

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    domainname: docker.local
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=username #optional
      - PASS=password #optional
    volumes:
      - ${USERDIR}/docker/transmission/config:/config
      - /media/linaro/GO/downloads:/downloads
      - ${USERDIR}/docker/transmission/watch:/watch
    ports:
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    labels: 
      - "traefik.http.routers.transmission.rule=Host(`transmission.dangernoodle.co.za`)"
      - "traefik.http.routers.transmission.entrypoints=http"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    domainname: docker.local
    networks:
      - proxy
    ports:
      - 8000:8000
    restart: unless-stopped
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USERDIR}/docker/portainer:/data
    labels: 
      - "traefik.http.routers.portainer.rule=Host(`portainer.dangernoodle.co.za`)"
      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      

  grocy:
    image: linuxserver/grocy:version-v2.7.1
    container_name: grocy
    domainname: docker.local
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    ports:
      - 8020:80
    volumes:
      - /home/linaro/docker/grocy:/config
    restart: unless-stopped
    labels: 
      - "traefik.http.routers.grocy.rule=Host(`grocy.dangernoodle.co.za`)"
      - "traefik.http.routers.grocy.entrypoints=http"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.grocy.loadbalancer.server.port=80"
